apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-api
  name: nginx-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-api
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
