apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev #(chú ý đổi Suffix trong cả 3 file)

bases:
  - ../../base
  
resources:
  - config-map.yaml

#demo patches json6902 replace dev
patches:
  - target:
      kind: Deployment
      name: nginx-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 8
        
  - target:
      kind: Deployment
      name: nginx-api        
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0
        value:
          name: newnametest
          image: httpd:alpine
