apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod #(chú ý đổi Suffix trong cả 3 file)

bases:
  - ../../base
  
resources:
  - config-map.yaml


#demo patches json6902 delete creationTimestamp
patches:
  - target:
      kind: Deployment
      name: nginx-api        
    patch: |-
      - op: remove
        path: /spec/template/metadata/creationTimestamp
  - target:
      kind: Deployment
      name: nginx-api        
    patch: |-
      - op: remove
        path: /metadata/creationTimestamp       