apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-api
  name: nginx-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30181
  selector:
    app: nginx-api
  type: NodePort
status:
  loadBalancer: {}
